const fs = require('fs');
const path = require('path');

/** Marker comment so stubs are identifiable in clones. */
const STUB_MARKER = 'Generated by Voyagerr Lens';

const CONFIG_JS_STUB = `/**
 * ${STUB_MARKER} — gitignored config/config.js was missing for Jest.
 * Replace with the real generated config when building the app.
 */
export default {
  env: {
    appName: 'TestApp',
    appType: 'yod',
    RELEASE_ENV: 'dev',
    CUSTOMER_ENV: 'test',
    NODE_ENV: 'test',
    __API__: 'http://localhost',
    __AZURE_AUTH__: 'http://localhost/azure',
    loginType: 'password',
    appHelp: '',
    appScheme: 'test'
  }
};
`;

const THEME_JS_STUB = `/**
 * ${STUB_MARKER} — gitignored config/theme.js was missing for Jest.
 */
export const palette_dark = (colPrimary) => ({
  palette: {
    type: 'dark',
    primary: { main: colPrimary || '#333333' },
    secondary: { main: '#212121' }
  }
});

export const palette_light = (colPrimary) => ({
  palette: {
    type: 'light',
    primary: { main: colPrimary || '#0055aa' },
    secondary: { main: '#FFFFFF' }
  }
});

export const getTheme = (colPrimary) => palette_light(colPrimary);
`;

/**
 * Write minimal stubs for gitignored Trapeze config files so Jest suites can load.
 * Only creates files that are missing; never overwrites a real generated config.
 *
 * @param {string} projectRoot - Jest package / clone root
 * @returns {{ wroteConfigJs: boolean, wroteThemeJs: boolean }}
 */
function ensureGitignoredConfigStubs(projectRoot) {
    const result = { wroteConfigJs: false, wroteThemeJs: false };
    if (!projectRoot) {
        return result;
    }

    const configDir = path.join(projectRoot, 'config');
    const indexPath = path.join(configDir, 'index.js');
    if (!fs.existsSync(indexPath)) {
        return result;
    }

    const configJsPath = path.join(configDir, 'config.js');
    if (!fs.existsSync(configJsPath)) {
        fs.writeFileSync(configJsPath, CONFIG_JS_STUB, 'utf8');
        result.wroteConfigJs = true;
        console.log(`[CodeAnalyzer] Wrote stub ${configJsPath} (gitignored config missing)`);
    }

    const themeJsPath = path.join(configDir, 'theme.js');
    if (!fs.existsSync(themeJsPath)) {
        fs.writeFileSync(themeJsPath, THEME_JS_STUB, 'utf8');
        result.wroteThemeJs = true;
        console.log(`[CodeAnalyzer] Wrote stub ${themeJsPath} (gitignored theme missing)`);
    }

    return result;
}

module.exports = {
    ensureGitignoredConfigStubs,
    STUB_MARKER
};
